Import javax.swing.event in legend, as the EventHandler use it in legend. About exception Caused by: java.lang.NoClassDefFoundError: javax.swing.event.ChangeEvent not found by org.orbisgis.legend [41]